sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Cu38324
  alioss:
    access-key-secret: AFXUMslYWJGvhyA2LefwQTA2Lp5kdx
    access-key-id: LTAI5tB1iSVAgR6fzj5LDJ8H
    bucket-name: sky-take-out-27fx
    endpoint: oss-cn-hangzhou.aliyuncs.com
  redis:
    host: localhost
    port: 6379
    password:
    database: 10


  wechat:
    appid: wx5c7f5acfbc744ca9
    secret: 51b408bad1fa92d0a8afd2c1fe33d671
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\software\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePat: C:\software\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://7eda8a2.r19.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://7eda8a2.r19.cpolar.top/notify/refundSuccess


